apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"gateway","namespace":"ingestion-ns","creationTimestamp":null,"labels":{"app":"gateway"}},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"gateway"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"gateway"}},"spec":{"containers":[{"name":"agnhost","image":"registry.k8s.io/e2e-test-images/agnhost:2.39","ports":[{"containerPort":8000}],"resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: "2025-06-20T20:34:08Z"
  generation: 1
  labels:
    app: gateway
  name: gateway
  namespace: ingestion-ns
  resourceVersion: "125837"
  uid: 5643477b-2c16-4a7d-9e92-347d2f5996ec
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: registry.k8s.io/e2e-test-images/agnhost:2.39
        imagePullPolicy: IfNotPresent
        name: agnhost
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
